
# Note: this file's config override the Netlify UI admin config

# production build
[build]
  base = "/"
  command = "yarn workspace jest-website-v2 netlify:ci:build"
  publish = "/website-v2/build"

# deploy preview build
[context.deploy-preview]
  command = "yarn workspace jest-website-v2 netlify:ci:deployPreview"

