language: node_js

node_js: 10

sudo: false

os:
  - windows
  - linux


before_install:
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
    choco install python;
    fi

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn run test-ci-partial
