language: node_js

node_js: 10

sudo: false

os:
  - windows
  - linux

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn run test-ci-partial
