environment:
  matrix:
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - curl -fsSL -o yarn.js https://github.com/yarnpkg/yarn/releases/download/v0.27.5/yarn-0.27.5.js
  - node ./yarn.js --version
  - node ./yarn.js install
  - node ./yarn.js run build

cache:
  - node_modules
  - .eslintcache

test_script:
  - node ./yarn.js run jest -- --color

# Don't actually build.
build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
