
# Note: this file's config override the Netlify UI admin config

# production build
[build]
  base = "/"
  command = "yarn workspace jest-website netlify:ci:production"
  publish = "/website/build"

# deploy preview build
[context.deploy-preview]
  base = "/"
  command = "yarn workspace jest-website netlify:ci:deployPreview"
  publish = "/website/build"

