aliases:
  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages
  - &install
    pkg-manager: yarn
    override-ci-command: yarn install && yarn build:js
    cache-path: ~/.yarn/berry/cache
    include-branch-in-cache-key: false

orbs:
  node: circleci/node@4.0.0
version: 2.1
jobs:
  test-node-10:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: 10
          install-npm: false
          install-yarn: true
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-jest-circus:
    executor: node/default
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
          install-yarn: true
      - node/install-packages: *install
      - run:
          command: JEST_CIRCUS=1 yarn test-ci-partial && JEST_CIRCUS=1 yarn test-leak
      - store_test_results:
          path: reports/junit

  test-node-12:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: 12
          install-npm: false
          install-yarn: true
      - node/install-packages: *install
      - run:
          command: yarn test-ci
      - store_test_results:
          path: reports/junit

  test-node-13:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: 13
          install-npm: false
          install-yarn: true
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-14:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: 14
          install-npm: false
          install-yarn: true
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-or-deploy-website:
    executor: node/default
    resource_class: large
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
          install-yarn: true
      - node/install-packages:  *install
      - run:
          name: Test or Deploy Jest Website
          command: ./.circleci/website.sh

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node-10
      - test-node-12
      - test-node-13
      - test-node-14 # current
      - test-jest-circus
      - test-or-deploy-website:
          filters: *filter-ignore-gh-pages
