version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test-node:
    parameters:
      node-version:
        type: string
    working_directory: ~/jest
    executor: node/default
    parallelism: 4
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --immutable && yarn build:js
          cache-path: ~/.yarn/berry/cache
          include-branch-in-cache-key: false
          app-dir: ~/jest
      - run:
          command: yarn test-ci-partial --shard=$(expr $CIRCLE_NODE_INDEX + 1)/$CIRCLE_NODE_TOTAL
      - store_test_results:
          path: reports/junit

# Workflows enables us to run multiple jobs in parallel
workflows:
  build-and-deploy:
    jobs:
      - test-node:
          name: test-node-partial-<< matrix.node-version >>
          matrix:
            parameters:
              node-version: ['14', '16', '18', '19']
