aliases:
  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

version: 2
jobs:
  lint-and-typecheck:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn --no-progress --frozen-lockfile
      - run: echo server.max_workers=1 >> .flowconfig
      - run: yarn lint --format junit -o reports/junit/js-lint-results.xml && yarn typecheck && yarn lint-es5-build --format junit -o reports/junit/js-es5-lint-results.xml  && yarn lint:md:ci && yarn check-copyright-headers
      - store_test_results:
          path: reports/junit

  test-node-6:
    working_directory: ~/jest
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: rm -rf examples/react-native && yarn --no-progress --frozen-lockfile --ignore-engines
      - run: yarn jest --clear-cache
      - run:
          # react-native does not work with node 6
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-8:
    working_directory: ~/jest
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn --no-progress --frozen-lockfile
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-10:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn --no-progress --frozen-lockfile
      - run:
          command: yarn test-ci
      - store_test_results:
          path: reports/junit

  test-jest-circus:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn --no-progress --frozen-lockfile
      - run:
          command: JEST_CIRCUS=1 yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-11:
    working_directory: ~/jest
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: yarn --no-progress --frozen-lockfile
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-browser:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: yarn --no-progress --frozen-lockfile
      - run: yarn test-ci-es5-build-in-browser

  test-or-deploy-website:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    resource_class: large
    steps:
      - checkout
      - run: yarn --no-progress --frozen-lockfile
      - run:
          name: Test or Deploy Jest Website
          command: ./.circleci/website.sh

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node-6
