name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test-macos:
    uses: ./.github/workflows/test.yml
    strategy:
      fail-fast: false
      matrix:
        shard: ['1/3', '2/3', '3/3']
    name: macOS with shard ${{ matrix.shard }}
    with:
      os: macos-latest
      shard: ${{ matrix.shard }}
